"""
Email Sender Module
Formats and sends summary reports via SNS/SES
Owner: Kelly (Reporting & Visualization Lead)

IMPLEMENTATION GUIDANCE:
This module sends reports generated by report_generator.py via SNS or SES.
Use the exact variable names specified below to ensure compatibility with
Nicole's lambda_handler.py integration.

IMPORTANT VARIABLE NAMES:
- report: Dict[str, any] - The output from generate_daily_report() or generate_weekly_report()
- recipients: List[str] - List of email addresses
- sns_topic_arn: str - SNS topic ARN (from environment variable SNS_TOPIC_ARN)
- html_content: str - HTML formatted email body
"""

import boto3
from typing import Dict, List


def send_report_email(report: Dict[str, any], recipients: List[str], sns_topic_arn: str = None):
    """
    Formats and sends summary report via SNS/SES.
    
    IMPLEMENTATION NOTES:
    - Input 'report' comes from generate_daily_report() or generate_weekly_report()
    - Use SNS topic ARN from environment variable SNS_TOPIC_ARN (or pass as parameter)
    - Format report using format_report_html() for email body
    - Subject line format: "MedTech Security Report - {report_type} - {date}"
    - Use boto3 sns.publish() to send
    
    Args:
        report: Report dictionary from generate_daily_report() or generate_weekly_report()
                Structure: {'date': ..., 'report_type': ..., 'summary': {...}}
        recipients: List of email addresses (strings)
        sns_topic_arn: Optional SNS topic ARN (if None, get from environment variable SNS_TOPIC_ARN)
    """
    # TODO: Kelly - Implement email sending via SNS/SES
    # Use format_report_html() to create email body
    # Subject: f"MedTech Security Report - {report['report_type']} - {report['date']}"
    # Use boto3.client('sns').publish(TopicArn=..., Message=..., Subject=...)
    pass


def format_report_html(report: Dict[str, any]) -> str:
    """
    Formats report as HTML email.
    
    IMPLEMENTATION NOTES:
    - Input 'report' has structure: {'date': ..., 'report_type': ..., 'summary': {...}}
    - Create readable HTML table or formatted text
    - Include all metrics from report['summary']['findings']
    - Use proper HTML structure with <html>, <body>, <table> tags
    
    Args:
        report: Report dictionary from generate_daily_report() or generate_weekly_report()
        
    Returns:
        HTML formatted string suitable for email body
    """
    # TODO: Kelly - Implement HTML formatting
    # Create HTML table showing:
    # - Report date and type
    # - Public S3 buckets count
    # - MFA compliance stats
    # - Security group violations
    # - CloudTrail status
    # - Failed login count
    pass

