"""
Email Sender Module
Formats and sends summary reports via SNS/SES
Owner: Kelly (Reporting & Visualization Lead)

INTERFACE NOTES:
This module sends reports generated by report_generator.py. The SNS topic ARN will
be available via environment variable SNS_TOPIC_ARN if needed.
"""

import boto3
from typing import Dict, List


def send_report_email(report: Dict[str, any], recipients: List[str], sns_topic_arn: str = None):
    """
    Formats and sends summary report via SNS/SES.
    
    Args:
        report: Report dictionary to send
        recipients: List of email addresses
        sns_topic_arn: Optional SNS topic ARN (if None, get from environment variable)
    """
    # TODO: Kelly - Implement email sending via SNS/SES
    pass


def format_report_html(report: Dict[str, any]) -> str:
    """
    Formats report as HTML email.
    
    Args:
        report: Report dictionary to format
        
    Returns:
        HTML formatted string suitable for email body
    """
    # TODO: Kelly - Implement HTML formatting
    pass

