"""
Email Sender Module
Formats and sends summary reports via SNS/SES
Owner: Kelly (Reporting & Visualization Lead)

INTERFACE NOTES:
This module sends reports generated by report_generator.py. The SNS topic ARN will
be available via environment variable SNS_TOPIC_ARN if needed.
"""

import os
import boto3
from typing import Dict, List

sns = boto3.client("sns")


def send_report_email(report: Dict[str, any], recipients: List[str], sns_topic_arn: str = None):
    """
    Formats and sends summary report via SNS.
    
    Args:
        report: Report dictionary to send
        recipients: List of email addresses (SNS requires them to be subscribed)
        sns_topic_arn: Optional SNS topic ARN (if None, obtain from environment variables)
    """
    
    # 1. Use environment variable if sns_topic_arn wasn't passed
    if sns_topic_arn is None:
        sns_topic_arn = os.environ.get("SNS_TOPIC_ARN")
        if sns_topic_arn is None:
            raise ValueError("SNS Topic ARN not provided and not found in environment variables.")

    # 2. Format HTML email body
    email_body_html = format_report_html(report)

    # 3. SNS sends emails as *plain text messages*, so we send:
    #    - A plain text summary
    #    - A link to the S3 reports (your report generator will include these in the dict)
    subject = f"[MedTech] {report.get('period', 'Daily').title()} Security Summary Report"

    # Plain text fallback for SNS
    text_summary = f"""
MedTech Security Summary Report

Period: {report.get('period')}
Generated At: {report.get('generated_at')}

JSON Report: {report.get('json_s3_path')}
CSV Report:  {report.get('csv_s3_path')}

(HTML version not supported directly by SNS, see S3 links above.)
"""

    # 4. Publish message to SNS topic
    sns.publish(
        TopicArn=sns_topic_arn,
        Subject=subject,
        Message=text_summary
    )


def format_report_html(report: Dict[str, any]) -> str:
    """
    Formats report as an HTML email.
    
    SNS does NOT support HTML formatting directly,
    but this function prepares HTML for SES or future upgrades.
    
    Returns:
        HTML formatted string suitable for SES email body.
    """
    
    # Extract metrics safely
    metrics = report.get("metrics", {})

    # Build table rows
    metric_rows = ""
    for metric_name, metric_data in metrics.items():
        latest = metric_data.get("latest", "N/A")
        maximum = metric_data.get("max", "N/A")
        average = metric_data.get("avg", "N/A")

        metric_rows += f"""
        <tr>
            <td style="padding: 6px; border: 1px solid #ccc;">{metric_name}</td>
            <td style="padding: 6px; border: 1px solid #ccc;">{latest}</td>
            <td style="padding: 6px; border: 1px solid #ccc;">{maximum}</td>
            <td style="padding: 6px; border: 1px solid #ccc;">{average}</td>
        </tr>
        """

    # Final HTML email
    html = f"""
    <html>
    <body>
        <h2>MedTech Security Summary Report</h2>

        <p><strong>Period:</strong> {report.get('period')}</p>
        <p><strong>Generated At:</strong> {report.get('generated_at')}</p>

        <h3>Metric Summary</h3>
        <table style="border-collapse: collapse; width: 600px;">
            <tr>
                <th style="padding: 6px; border: 1px solid #ccc; background-color: #f2f2f2;">Metric</th>
                <th style="padding: 6px; border: 1px solid #ccc; background-color: #f2f2f2;">Latest</th>
                <th style="padding: 6px; border: 1px solid #ccc; background-color: #f2f2f2;">Max</th>
                <th style="padding: 6px; border: 1px solid #ccc; background-color: #f2f2f2;">Average</th>
            </tr>
            {metric_rows}
        </table>

        <h3>Download Full Reports</h3>
        <p><a href="{report.get('json_s3_path')}">JSON Report</a></p>
        <p><a href="{report.get('csv_s3_path')}">CSV Report</a></p>
    </body>
    </html>
    """

    return html
